dataset_name: 'CIFAR10'
mean: [0.4914, 0.4822, 0.4465]
std: [0.2023, 0.1994, 0.2010]
train_batch_size: 64
learning_rate: 3.0e-4
num_epochs: 20
input_size: [32,32]
input_channels: 3
channels: 32
layers_num_range: [2, 4, 6, 8, 10]
kernel_size: 3
classes: 10
