model:
  class: conv
  hidden_channels: 64
  layers_num: 1
  kernel_size: 3
  input_channels: 1
  output_channels: 16
  input_sizes: [28, 28]
  variable_param: hidden_channels
  variable_param_grid: [64, 128, 256, 512, 1024]
  padding: 1
  classes: 10

logging:
  savefig_path: 'results/FashionMNIST/conv_channels_ln1.png'

dataset:
  name: 'FashionMNIST'
  load_path: 'data/'
  transform_params:
    mean: [0.5]
    std: [0.5]
  batch_size: 64
  size: -1

train_params:
  optimizer: Adam
  learning_rate: 3.0e-4
  num_epochs: 50

device: 'cuda'

delta_vis_params:
  mode: random-subspace-proj
  mode_params:
    estim_func: abs
    sigma: 8
    dim: 2
  num_samples: 64

visualize:
  smooth_window: 10
  train_loss_smooth_window: 20
