model:
  class: mlp
  input_channels: 1
  input_sizes: [28, 28]
  hidden: 128
  layers_num: 6
  variable_param: hidden
  variable_param_grid: [64, 128, 256, 512, 1024]
  classes: 10

logging:
  savefig_path: 'results/FashionMNIST/mlp_hidden_sigm8.png'

dataset:
  name: 'FashionMNIST'
  load_path: 'data/'
  transform_params:
    mean: [0.5]
    std: [0.5]
  batch_size: 64
  size: -1

train_params:
  optimizer: Adam
  learning_rate: 3.0e-4
  num_epochs: 50

device: 'cuda'

delta_vis_params:
  mode: random-subspace-proj
  mode_params:
    estim_func: abs
    sigma: 8
    dim: 2
  num_samples: 64

visualize:
  smooth_window: 10
  train_loss_smooth_window: 20
